const languages = {
  it:{navApps:'Applicazioni',navAbout:'Il marchio',languageLabel:'Lingua',eyebrow:'SOFTWARE INDIPENDENTE · DAL 2024',heroTitle:'Strumenti utili.<br><em>Idee concrete.</em>',heroLead:'Applicazioni curate per risolvere problemi reali, con attenzione alla privacy, alla chiarezza e a chi le usa ogni giorno.',explore:'Scopri le applicazioni',heroFoot:'PROGETTATE PER LE PERSONE. PENSATE PER DURARE.',collection:'LA COLLEZIONE',appsTitle:'Applicazioni',aboutEyebrow:'UN PICCOLO STUDIO, IDEE UTILI',aboutTitle:'La tecnologia<br>deve aiutare.',aboutText:'Vis-K crea software indipendente con uno scopo semplice: rendere più accessibili attività complesse e togliere attrito dalla vita digitale. Niente rumore, solo strumenti che fanno il loro lavoro.',footer:'Software indipendente. Fatto con cura.',backTop:'TORNA SU ↑',details:'Tutti i dettagli',visit:'Visita il sito',store:'Microsoft Store',loading:'Caricamento applicazioni…',error:'Non è stato possibile caricare i contenuti.',apps:['Strategia · Gioco','Lavoro · Accessibilità','Sviluppatori · Affidabilità','IA · Strumenti locali']},
  en:{navApps:'Apps',navAbout:'About Vis-K',languageLabel:'Language',eyebrow:'INDEPENDENT SOFTWARE · SINCE 2024',heroTitle:'Useful tools.<br><em>Thoughtful ideas.</em>',heroLead:'Carefully made apps that solve real problems, with attention to privacy, clarity and the people who use them every day.',explore:'Explore the apps',heroFoot:'MADE FOR PEOPLE. BUILT TO LAST.',collection:'THE COLLECTION',appsTitle:'Applications',aboutEyebrow:'A SMALL STUDIO, USEFUL IDEAS',aboutTitle:'Technology<br>should help.',aboutText:'Vis-K makes independent software with a simple purpose: make complex tasks more accessible and remove friction from digital life. No noise, just tools that do their job.',footer:'Independent software. Made with care.',backTop:'BACK TO TOP ↑',details:'All details',visit:'Visit website',store:'Microsoft Store',loading:'Loading applications…',error:'Could not load the content.',apps:['Strategy · Game','Work · Accessibility','Developers · Reliability','AI · Local tools']},
  es:{navApps:'Aplicaciones',navAbout:'La marca',languageLabel:'Idioma',eyebrow:'SOFTWARE INDEPENDIENTE · DESDE 2024',heroTitle:'Herramientas útiles.<br><em>Ideas concretas.</em>',heroLead:'Aplicaciones cuidadas para resolver problemas reales, con atención a la privacidad, la claridad y quienes las usan cada día.',explore:'Descubre las aplicaciones',heroFoot:'DISEÑADAS PARA LAS PERSONAS. HECHAS PARA DURAR.',collection:'LA COLECCIÓN',appsTitle:'Aplicaciones',aboutEyebrow:'UN PEQUEÑO ESTUDIO, IDEAS ÚTILES',aboutTitle:'La tecnología<br>debe ayudar.',aboutText:'Vis-K crea software independiente con un propósito sencillo: facilitar las tareas complejas y reducir la fricción en la vida digital. Sin ruido, solo herramientas que cumplen su función.',footer:'Software independiente. Hecho con cuidado.',backTop:'VOLVER ARRIBA ↑',details:'Ver todos los detalles',visit:'Visitar sitio web',store:'Microsoft Store',loading:'Cargando aplicaciones…',error:'No se pudo cargar el contenido.',apps:['Estrategia · Juego','Trabajo · Accesibilidad','Desarrolladores · Fiabilidad','IA · Herramientas locales']},
  fr:{navApps:'Applications',navAbout:'La marque',languageLabel:'Langue',eyebrow:'LOGICIEL INDÉPENDANT · DEPUIS 2024',heroTitle:'Des outils utiles.<br><em>Des idées concrètes.</em>',heroLead:'Des applications conçues pour résoudre de vrais problèmes, avec une attention particulière à la vie privée, à la clarté et à leurs utilisateurs.',explore:'Découvrir les applications',heroFoot:'CONÇUES POUR LES PERSONNES. FAITES POUR DURER.',collection:'LA COLLECTION',appsTitle:'Applications',aboutEyebrow:'UN PETIT STUDIO, DES IDÉES UTILES',aboutTitle:'La technologie<br>doit aider.',aboutText:'Vis-K crée des logiciels indépendants avec un objectif simple : rendre les tâches complexes plus accessibles et simplifier la vie numérique. Pas de superflu, juste des outils efficaces.',footer:'Logiciels indépendants. Conçus avec soin.',backTop:'HAUT DE PAGE ↑',details:'Tous les détails',visit:'Visiter le site',store:'Microsoft Store',loading:'Chargement des applications…',error:'Impossible de charger le contenu.',apps:['Stratégie · Jeu','Travail · Accessibilité','Développeurs · Fiabilité','IA · Outils locaux']},
  de:{navApps:'Apps',navAbout:'Über Vis-K',languageLabel:'Sprache',eyebrow:'UNABHÄNGIGE SOFTWARE · SEIT 2024',heroTitle:'Nützliche Tools.<br><em>Klare Ideen.</em>',heroLead:'Sorgfältig entwickelte Apps für echte Probleme – mit besonderem Augenmerk auf Datenschutz, Verständlichkeit und die Menschen, die sie täglich nutzen.',explore:'Apps entdecken',heroFoot:'FÜR MENSCHEN ENTWICKELT. AUF DAUER GEMACHT.',collection:'DIE SAMMLUNG',appsTitle:'Anwendungen',aboutEyebrow:'EIN KLEINES STUDIO, NÜTZLICHE IDEEN',aboutTitle:'Technologie<br>soll helfen.',aboutText:'Vis-K entwickelt unabhängige Software mit einem einfachen Ziel: komplexe Aufgaben zugänglicher machen und den digitalen Alltag erleichtern. Kein Ballast, nur Werkzeuge, die ihren Zweck erfüllen.',footer:'Unabhängige Software. Mit Sorgfalt gemacht.',backTop:'NACH OBEN ↑',details:'Alle Details',visit:'Website besuchen',store:'Microsoft Store',loading:'Anwendungen werden geladen…',error:'Inhalte konnten nicht geladen werden.',apps:['Strategie · Spiel','Arbeit · Barrierefreiheit','Entwickler · Zuverlässigkeit','KI · Lokale Tools']},
  zh:{navApps:'应用',navAbout:'关于 Vis-K',languageLabel:'语言',eyebrow:'独立软件 · 始于 2024',heroTitle:'实用工具。<br><em>切实创意。</em>',heroLead:'精心打造的应用，解决真实问题，关注隐私、清晰易用，以及每天使用它们的人。',explore:'探索应用',heroFoot:'为人而设计，经久耐用。',collection:'产品精选',appsTitle:'应用程序',aboutEyebrow:'小型工作室，实用好点子',aboutTitle:'科技<br>应该带来帮助。',aboutText:'Vis-K 专注于独立软件，目标很简单：让复杂任务更易上手，让数字生活更顺畅。不堆砌噱头，只提供真正好用的工具。',footer:'独立软件，用心打造。',backTop:'返回顶部 ↑',details:'查看全部详情',visit:'访问网站',store:'Microsoft Store',loading:'正在加载应用…',error:'无法加载内容。',apps:['策略 · 游戏','工作 · 无障碍','开发者 · 可靠性','人工智能 · 本地工具']}
};
const productsRoot=document.querySelector('#products'), languageSelect=document.querySelector('#language'), dialog=document.querySelector('#details');
let products=[];
function applyLanguage(lang){const t=languages[lang]||languages.it;document.documentElement.lang=lang;document.title=`Vis-K — ${t.eyebrow.split(' · ')[0]}`;languageSelect.value=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key])el.innerHTML=t[key]});renderProducts(lang,t);try{localStorage.setItem('visk-language',lang)}catch{}}
function renderProducts(lang,t){if(!products.length){productsRoot.innerHTML=`<p class="loading">${t.loading}</p>`;return}productsRoot.innerHTML=products.map((p,i)=>`<article class="product-card"><div class="product-visual"><img src="${p.images[lang]||p.images.en}" alt="${p.name} — ${t.apps[i]}" loading="lazy"><span class="product-number">0${i+1} / 04</span></div><div class="product-info"><div class="product-meta"><span>${t.apps[i]}</span><span class="tag">VIS-K / ${String(i+1).padStart(2,'0')}</span></div><h3>${p.name}</h3><p>${p.translations[lang]?.short||p.translations.en.short}</p><div class="card-actions"><button class="text-button detail-trigger" data-index="${i}">${t.details} ↗</button><a class="store-button" href="${p.store}" target="_blank" rel="noreferrer">${t.store} ↗</a></div></div></article>`).join('');productsRoot.querySelectorAll('.detail-trigger').forEach(b=>b.addEventListener('click',()=>showDetails(Number(b.dataset.index),lang,t)))}
function formatDescription(source){return source.trim().split(/\n\s*\n/).map(block=>{const lines=block.trim().split('\n').map(line=>line.trim()).filter(Boolean);if(lines.length&&lines.every(line=>/^[-•]\s/.test(line)))return `<ul>${lines.map(line=>`<li>${escapeHtml(line.replace(/^[-•]\s/,''))}</li>`).join('')}</ul>`;if(lines.length===1&&lines[0].length<100&&/[A-ZÀ-Ý]/.test(lines[0])&&lines[0]===lines[0].toLocaleUpperCase())return `<h3>${escapeHtml(lines[0])}</h3>`;return `<p>${lines.map(escapeHtml).join('<br>')}</p>`}).join('')}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showDetails(i,lang,t){const p=products[i],data=p.translations[lang]||p.translations.en;document.querySelector('#dialog-title').textContent=p.name;document.querySelector('#dialog-kicker').textContent=`VIS-K / ${String(i+1).padStart(2,'0')} — ${p.name.toUpperCase()}`;document.querySelector('#dialog-body').innerHTML=formatDescription(data.full);document.querySelector('#dialog-actions').innerHTML=`<a href="${p.page}" target="_blank" rel="noreferrer">${t.visit} ↗</a><a href="${p.store}" target="_blank" rel="noreferrer">${t.store} ↗</a>`;dialog.showModal()}
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog.open)dialog.close()});languageSelect.addEventListener('change',()=>applyLanguage(languageSelect.value));
products=window.VISK_PRODUCTS||[];if(products.length)applyLanguage(languageSelect.value);else productsRoot.textContent=languages.it.error;
let initial='it';try{const saved=localStorage.getItem('visk-language');if(saved&&languages[saved])initial=saved;else{const preferred=(navigator.language||'').slice(0,2);if(languages[preferred])initial=preferred}}catch{}applyLanguage(initial);
